#!/bin/bash
# iptables com regras de firewall
############ EXTRA STUFF TO HELP HIGH TRAFFIC (DDOS) ##################

###################################################################################################################
# _|___|___|___|___|___|___|___|___|___|___|___|___|                                                             ##
# ___|___|___|___|___|___|___|___|___|___|___|___|__        IPTables: Linux's Main line of Defense               ##
# _|___|___|___|___|___|___|___|___|___|___|___|___|        IPTables: Linux's way of saying no to DoS kids       ##
# ___|___|___|___|___|___|___|___|___|___|___|___|__                                                             ##    
# _|___|___|___|___|___|___|___|___|___|___|___|___|        Version 1.0.0 -                                      ##
# ___|___|___|___|___|___|___|___|___|___|___|___|__        IPTables Script created by p0w3r0ff                  ##
# _|___|___|___|___|___|___|___|___|___|___|___|___|                                                             ##
# ___|___|___|___|___|___|___|___|___|___|___|___|__        Sources used and Studied;                            ##
# _|___|___|___|___|___|___|___|___|___|___|___|___|                                                             ##
# ___|___|___|___|___|___|___|___|___|___|___|___|__     http://ipset.netfilter.org/iptables.man.html            ##
# _|___|___|___|___|___|___|___|___|___|___|___|___|                                                             ##
# ___|___|___|___|___|___|___|___|___|___|___|___|__                                                             ##
###################################################################################################################

# Instalar e configurar Fail2Ban
sudo apt-get update
sudo apt-get install -y fail2ban

# Configurar jail.local para SSH e Apache
cat <<EOL | sudo tee /etc/fail2ban/jail.local
[sshd]
enabled = true

[apache]
enabled = true
EOL

# Reiniciar Fail2Ban
sudo service fail2ban restart

# Instalar e configurar ModSecurity
sudo apt-get install -y libapache2-mod-security2
if [ -f /etc/modsecurity/modsecurity.conf-recommended ]; then
    sudo cp /etc/modsecurity/modsecurity.conf-recommended /etc/modsecurity/modsecurity.conf
fi

# Configurar SecRuleEngine
sudo sed -i 's/SecRuleEngine DetectionOnly/SecRuleEngine On/' /etc/modsecurity/modsecurity.conf

# Reiniciar Apache
sudo service apache2 restart

# Configurar iptables para bloquear tráfego de IP específico (Exemplo)
# sudo iptables -A INPUT -s 1.2.3.4 -j DROP

# Configurar iptables para mitigar ataques DDoS (limitar conexões)
sudo iptables -A INPUT -p tcp --syn -m connlimit --connlimit-above 50 -j DROP

# Configurar iptables para limitar a taxa de novas conexões
INTERFACE=$(ip route | grep default | awk '{print $5}' | head -n1)
if [ -n "$INTERFACE" ]; then
    sudo iptables -A INPUT -p tcp --dport 80 -i "$INTERFACE" -m state --state NEW -m recent --set
    sudo iptables -A INPUT -p tcp --dport 80 -i "$INTERFACE" -m state --state NEW -m recent --update --seconds 60 --hitcount 20 -j DROP
fi

# Configurar iptables para evitar ataques ICMP e UDP flood
sudo iptables -A INPUT -p icmp --icmp-type echo-request -m limit --limit 1/s -j ACCEPT
sudo iptables -A INPUT -p icmp -j DROP
sudo iptables -A INPUT -p udp --dport 53 -m limit --limit 1/s -j ACCEPT
sudo iptables -A INPUT -p udp -j DROP

# Salvar regras iptables (tenta usar iptables-save se netfilter-persistent falhar)
if command -v netfilter-persistent &> /dev/null; then
    sudo service netfilter-persistent save
    sudo service netfilter-persistent reload
else
    sudo iptables-save | sudo tee /etc/iptables/rules.v4
fi

echo "Script concluído!"
